"""rename columns

Revision ID: 903318c0a985
Revises: c73b2c28caeb
Create Date: 2024-07-10 13:44:28.059261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903318c0a985'
down_revision = 'c73b2c28caeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('group')

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('group')

    # ### end Alembic commands ###
